language: java

jdk:
  - oraclejdk8

env:
  global:
    - NODE_VERSION=stable
    - ANDROID_HOME=$HOME/android-sdk-linux
    - PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

git:
  depth: 3

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/
    - $HOME/.m2
    - $ANDROID_HOME/licenses/

before_cache:
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - set -e
  - ./scripts/installAndroidSDK.sh


install:


script:
    - echo no | android create avd --force -n test -t android-23 --abi x86
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
    - ./gradlew installDebug


after_script:
  - echo "BUILD FINISHED"

after_success:
  - bash echo yata!
